### ISSUE TITLE
milestones to include non-Carpentry lessons?

### ISSUE THREAD

**Issue by tracykteal** [carpentries/2018-r-consortium-lessondown-proposal#3]
Since we're proposing that the template can be extended outside Carpentries lessons, could a non-Carpentry lesson or two be included in the milestones? I know we have instructors who teach their own content. Maybe some of those would be good to try? Karl Broman or Pat Schloss could be candidates for this. I also have some, e.g. https://github.com/edamame-course/BLAST-tutorial/blob/master/running-BLAST.md

**Comment by fmichonneau** [comment]
Good point, I added a section about other lessons in the timeline.
