### ISSUE TITLE
Assessment!

### ISSUE THREAD

**Issue by tracykteal** [carpentries/2018-r-consortium-lessondown-proposal#8]
Could we add in something about how it would make outcomes or exercises easier to assess, or build assessment into the lesson development process? Could add Kari to the proposal too. Not sure if whole list of contributors is needed though.

**Comment by fmichonneau** [comment]
I think this is more part of the longer-term goal. We could collaborate with RStudio or DataCamp to use their cloud systems to get interactive answers to the challenges.
